jpa:
  show-sql: true
  hibernate:
    ddl-auto: update

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    credentials:
      accessKey: accessKey
      secretKey: secretKey
    s3:
      bucket: bucket
    region:
      static: region
    stack:
      auto: false



---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
